Remove ChallengePriority.NONE
nachtm/atlas-checks pull request #8
Opened 2018-12-13 19:58 UTC by nachtm

### Description:

There is no corresponding value to ChallengePriority.NONE on the MapRoulette side. Trying to upload a challenge with ChallengePriority.NONE, or its integer value (-1) leads to poorly visualized checks. Compare the result of an upload with ChallengePriority.NONE:
<img width="1670" alt="screen shot 2018-12-13 at 11 39 21 am" src="https://user-images.githubusercontent.com/12106730/49963050-ce6f0a80-fecb-11e8-8aaa-26e0649ecaf5.png">
to the exact same run, but with ChallengePriority.MEDIUM:
<img width="1666" alt="screen shot 2018-12-13 at 11 38 52 am" src="https://user-images.githubusercontent.com/12106730/49963083-de86ea00-fecb-11e8-8c3a-0ba4eead233c.png">

In addition, when uploading tasks directly through the MapRoulette UI, you cannot select a default priority of none:
![screen shot 2018-12-13 at 11 49 47 am](https://user-images.githubusercontent.com/12106730/49963581-3eca5b80-fecd-11e8-9c25-1f75bbea8cf5.png)

So, this PR removes the NONE value from the enum, and updates the deserializer to default to LOW.

### Potential Impact:

Any library using ChallengePriority.NONE will have to update those values to be something that matches the MapRoulette options.

### Unit Test Approach:

Updated a unit test to expect a default of ChallengePriority.LOW. Also ran atlas-checks with maproulette uploads before and after.

### Test Results:

All tests passing. Much better results on maproulette on this branch compared to dev.

2018-12-14 06:50 UTC, danielduhh requested changes
Instead of removing, can we just make sure that the default priority is always low, unless otherwise specified ?

2018-12-14 17:49 UTC, nachtm commented
@danielduhh Sure! I've made that change in my most recent commit. 

What do you think about adding a deprecated tag onto `NONE`?

2018-12-14 17:53 UTC, danielduhh commented
Good question - check out the maproulette docs, does it mention anything about challenge priorities ? http://maproulette2.geo.apple.com/docs/swagger-ui/index.html?url=/assets/swagger.json#/ @nachtm

2018-12-17 04:27 UTC, danielduhh commented
Thank you; I'm all for Deprecating NONE. Can you make a note that -1 isn't handled, via the public docs -> https://maproulette.org/docs/swagger-ui/index.html?url=/assets/swagger.json#/

2018-12-17 04:27 UTC, danielduhh approved these changes

2018-12-17 17:55 UTC, Bentleysb approved these changes
LGTM

2018-12-17 17:58 UTC, sayas01 approved these changes
Looks good!

2018-12-17 19:33 UTC, closed without merging